### ISSUE TITLE
Error after accepting colleague request

### ISSUE THREAD

**Issue by gabrielcossette** [gctools-outilsgc/gccollab#149] opened 2017-06-08 01:42 UTC
Hi!

After I accept a colleague request, it works but I get the following error page (happened two times now):

> Bad request
> Sorry. The request is invalid or incomplete.

URL; https://gccollab.ca/ajax/view/gc_profile_nudge/profile_nudge

Let me know if you want me to send you a colleague request to test it out on your side ;)

**Comment by markwooff** [comment] 2017-06-09 13:26
Thanks @gabrielcossette, I believe I know the cause of this one (the URL looks familiar). Going to put in a fix over the weekend.

**Comment by markwooff** [comment] 2017-06-14 15:11
Issue has been fixed with 6687b388f7459869f9ecece34a34dddb17acf739. In case you were curious about the issue, the JS was trying to fire an AJAX call before the page was finished loading. That AJAX view is located at the `/ajax/view/gc_profile_nudge/profile_nudge` url you mentioned.

**Closed as completed by markwooff** 2017-06-14 15:11 UTC
