### ISSUE TITLE
GCcollab Wiki- Download as PDF gives Error

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#317] opened 2018-04-17 15:07 UTC
As a user, I want to be able to download a GCcollab Wiki page as PDF.

Currently, if I click 'Download as PDF' I get the following error:
![image](https://user-images.githubusercontent.com/29754185/38878626-6075d33c-422f-11e8-9f07-e26d1e0408ee.png)
![image](https://user-images.githubusercontent.com/29754185/38878674-7aeeb242-422f-11e8-88af-d2975bd04cb7.png)

**Comment by klecuyer** [comment] 2018-04-17 16:14
https://support.gctools-outilsgc.ca/helpdesk/tickets/3098

**Comment by LemieuxGen** [comment] 2018-04-24 12:01
@klecuyer, could you move this issue in the GCpedia repo? until we have a new way forward, all the wiki related issues should be in the GCpedia repo. You can close this one once the issue is in the other repo. Thanks! :)

**Closed as completed** 2018-04-24 12:45 UTC
