### ISSUE TITLE
Fatal error when interacting with user profiles with high number of colleagues

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gccollab#313] opened 2018-04-11 20:10 UTC
When a user (with a large amount of colleagues) clicks on the  "New collection" button to create a new colleague collection an error message is generated:

 "Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 128 bytes) in /var/www/html/gccollab/engine/classes/Elgg/Database.php on line 351".

The error is also received when trying to invite colleagues to a group.

I suspect this is a similar issue we had in GCconnex brought up in this (resolved) ticket: https://github.com/gctools-outilsgc/gcconnex/issues/1699

User reporting issue: Justin.Patrick

**Comment by KevinChagnon** [comment] 2018-04-11 20:11
https://github.com/Phanoix/gccollab-help/issues/29

**Comment by KevinChagnon** [comment] 2018-04-17 15:39
This caused Justin to lose access to his GCcollab profile.  Other users, including myself, also get a fatal Error when trying to access his profile:


Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 32 bytes) in /var/www/html/gccollab/engine/classes/Elgg/Database.php on line 351

**Comment by klecuyer** [comment] 2018-04-17 17:19
Other users reporting the same error when clicking on 'My Colleagues'
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 83 bytes) in /var/www/html/gccollab/engine/classes/Elgg/Database.php on line 351

**Comment by klecuyer** [comment] 2018-04-17 17:20
https://support.gctools-outilsgc.ca/helpdesk/tickets/3111

**Comment by markwooff** [comment] 2018-04-17 18:16
These error messages are appearing due to the large database query caused by the large amount of users trying to be displayed. In the case of viewing Justin's profile page, the culprit is from trying to display the total number of colleagues in the sidebar:

![image](https://user-images.githubusercontent.com/5591488/38888520-de7958d4-4249-11e8-9ee6-917c09802be2.png)

An easy solution would just be to remove the number in brackets and just have the text show "View All Colleagues" instead.

**Comment by KevinChagnon** [comment] 2018-04-23 16:46
Are we proceeding with @markwooff 's recommendation: "remove the number in brackets and just have the text show "View All Colleagues" instead" ?

@LemieuxGen

**Comment by klecuyer** [comment] 2018-04-27 13:36
Other users reporting this as well with a high number of colleagues, not just for collections but for clicking on their profile, or accepting a colleague request. Giving fatal error

![image](https://user-images.githubusercontent.com/29754185/39365185-73545916-49fe-11e8-8ee9-6b7ec5dbba26.png)

https://gccollab.ca/profile/Taran.Wasson

**Comment by markwooff** [comment] 2018-04-30 17:35
Colleague count has been removed from the profile page. Closing issue.

**Comment by KevinChagnon** [comment] 2018-04-30 18:01
First item in this ticket is still an issue: 
When a user (with a large amount of colleagues) clicks on the "New collection" button to create a new colleague collection an error message is generated:

"Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 128 bytes) in /var/www/html/gccollab/engine/classes/Elgg/Database.php on line 351"

Justin Patrick now has access to his profile (so do others) but he still Errors out when trying to create a Colleague Collection

@markwooff

**Comment by markwooff** [comment] 2018-05-01 12:41
I can see the issue now and it's due to the large number of colleagues being presented to a user with many colleagues. We can certainly limit the number of colleagues so that the page loads but then not all users will be selectable from this screen:

![image](https://user-images.githubusercontent.com/5591488/39473151-5c2b059e-4d1b-11e8-9c92-b95672f126ff.png)

Wondering if we should just limit the number of users shown or have an input text field that would show a user upon typing (similar to the tagging feature). Thoughts?

**Comment by markwooff** [comment] 2018-05-01 12:46
Just tested the list and the max number we could show is 1600 colleagues before the page crashes.

**Comment by KevinChagnon** [comment] 2018-05-01 14:26
@LemieuxGen

**Comment by LemieuxGen** [comment] 2018-05-09 19:48
@markwooff how does it work for when users want to invite their colleagues to a group? The same list of colleagues appear on that invitation page. Does it crash as well? and if not, can we replicate that list? 
Other question is: if we limit to 1600 colleagues, will the filter look for the other colleagues not included in the list? I'm just worried that a cap on the colleagues will create issues. Depending on the answers to these questions, I would prefer using a input field text that shows the user upon typing.

**Comment by markwooff** [comment] 2018-05-10 12:48
@LemieuxGen yes the **Invite users to join this group** page is what this should be modelled after. The text field there doesn't need to load all 1600+ users before they are selectable which ensures the page doesn't crash 😄 

Limiting the 1600 users on the current **New colleague collection** page would make it so that the users outside of the 1600 would not be selectable. So between these two options, this is not the ideal solution.

**Comment by LemieuxGen** [comment] 2018-05-10 13:12
@markwooff Great! then lets use the model from the **Invite users to join this group** page. Let me know if you have all you need to proceed. Thanks!

**Comment by markwooff** [comment] 2018-05-11 05:09
The change has been completed to convert the old layout with the autocompletion text field as it appears on the **Invite users to join this group** page. Please take a look at the dev site to see the working example at https://dev.gccollab.ca/collections/owner/ and creating a "New collection".

**Comment by LemieuxGen** [comment] 2018-05-17 12:25
@sabrinatbs Could you please test the change on dev based on the changes identified in this thread? please add your comments, issues (if any) in Github directly. Thanks!

**Comment by sabrinatbs** [comment] 2018-05-17 13:29
Tested this on the https://dev.gccollab.ca/collections/owner/ and there are no fatal errors that were detected.

**Closed as completed** 2018-05-23 19:00 UTC
Labels: Type: Bug

**Comment by markwooff** [comment] 2018-05-23 19:01
**Colleague collections** now uses the same autocomplete style as it does in the **Invite users to join this group** page. Fatal error should no longer be received for users with large amounts of colleagues.
